name: Fetch latest DarkSky Weather data for Cardiff

on:
  repository_dispatch:
  schedule:
    - cron:  '10,40 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        mkdir -p cardiff/darksky && cd cardiff/darksky
        wget -q -O weather_new.json "https://api.darksky.net/forecast/256d6f395303ef80d4414e5a116279f1/51.4816,3.1791"
        jq . weather_new.json > weather.json
        rm weather_new.json
    - name: Commit and push data if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest DarkSky Weather for Cardiff: ${timestamp}" || exit 0
        git push
